### ISSUE TITLE
TypeError when reading res1d

### ISSUE THREAD

**Issue by Achton-Boel** [DHI/mikeio1d#3]
Hi,

Trying to read my own (and several others) .res1d I get the following error:

res1d = Res1D(file_path)
df = res1d.read()
Traceback (most recent call last):

  File "<ipython-input-17-9742ac5b76ce>", line 2, in <module>
    df = res1d.read()

  File "C:\Users\aac\Anaconda3\lib\site-packages\mikeio1d\res1d.py", line 159, in read
    return self.read_all()

  File "C:\Users\aac\Anaconda3\lib\site-packages\mikeio1d\res1d.py", line 174, in read_all
    for values, col_name in Res1D.get_values(

  File "C:\Users\aac\Anaconda3\lib\site-packages\mikeio1d\res1d.py", line 188, in get_values
    col_name = col_name_delimiter.join([data_item.Quantity.Id, name])

TypeError: sequence item 1: expected str instance, NoneType found

I've tried with the .res1d file which you have in the test folder, worked fine.
I'm using MIKE URBAN 2020 Update 1

**Comment by gedaskir** [comment]
Hello, I would need to get a failing res1d file example to figure out what is happening. Could you provide a one?

**Comment by gedaskir** [comment]
The issue seems to be not there with development mikeio1d 0.2
