### ISSUE TITLE
ImportError: cannot import name 'ResultDataQuery' from 'DHI.Mike1D.ResultDataAccess' (unknown location)

### ISSUE THREAD

**Issue by lj512lj512** [DHI/mikeio1d#5]
from mikeio1d.res1d import Res1D, QueryDataReach
Traceback (most recent call last):

  File "<ipython-input-25-fa3dbe01d567>", line 1, in <module>
    from mikeio1d.res1d import Res1D, QueryDataReach

  File "C:\Anaconda3\lib\site-packages\mikeio1d\res1d.py", line 25, in <module>
    from DHI.Mike1D.ResultDataAccess import ResultData, ResultDataQuery

ImportError: cannot import name 'ResultDataQuery' from 'DHI.Mike1D.ResultDataAccess' (unknown location)

**Comment by lj512lj512** [comment]
Solved.
