### ISSUE TITLE
mikeio1d conflicts with mikeplus

### ISSUE THREAD

**Issue by ZhaoNianZH** [DHI/mikeio1d#89]
**Describe the bug**
`mikeio1d.res1d.Res1D` module conflicts with `mikeplus.Engine1D` module.  
Currently the `mikeplus` package is in beta and contains limited functionality, when I loaded `Engine1D` form `mikeplus`, I noticed that mikeio1d could not read the results properly. The following error is returned:
```
Python.Runtime.PythonException: DHI.Mike1D.ResultDataAccess.ResultData value cannot be converted to DHI.Mike1D.ResultDataAccess.ResultData

The above exception was the direct cause of the following exception:

System.ArgumentException: DHI.Mike1D.ResultDataAccess.ResultData value cannot be converted to DHI.Mike1D.ResultDataAccess.ResultData in method Void .ctor(DHI.Mike1D.ResultDataAccess.ResultData) ---> Python.Runtime.PythonException: DHI.Mike1D.ResultDataAccess.ResultData value cannot be converted to DHI.Mike1D.ResultDataAccess.ResultData   
   --- End of inner exception stack trace ---

The above exception was the direct cause of the following exception:

System.AggregateException: One or more errors occurred. ---> System.ArgumentException: DHI.Mike1D.ResultDataAccess.ResultData value cannot be converted to DHI.Mike1D.ResultDataAccess.ResultData in method Void .ctor(DHI.Mike1D.ResultDataAccess.ResultData) ---> Python.Runtime.PythonException: DHI.Mike1D.ResultDataAccess.ResultData value cannot be converted to DHI.Mike1D.ResultDataAccess.ResultData
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: DHI.Mike1D.ResultDataAccess.ResultData value cannot be converted to DHI.Mike1D.ResultDataAccess.ResultData in method Void .ctor(DHI.Mike1D.ResultDataAccess.ResultData) ---> Python.Runtime.PythonException: DHI.Mike1D.ResultDataAccess.ResultData value cannot be converted to DHI.Mike1D.ResultDataAccess.ResultData
   --- End of inner exception stack trace ---<---

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:/****/****/mikepluspy-main/notebooks/test.py", line 21, in <module>
    result_ = mikeio1d.res1d.Res1D(r'D:\****\****\mikepluspy-main\tests\testdata\Db\Sirius\Sirius_m1d - Result Files\Sirius_1_DEMOBaseDefault_Network_HD.res1d')    
  File "C:\Users\****\.conda\envs\python38\lib\site-packages\mikeio1d\res1d.py", line 113, in __init__
    self.result_reader = ResultReaderCreator.create(
  File "C:\Users\****\.conda\envs\python38\lib\site-packages\mikeio1d\result_reader_writer\result_reader_creator.py", line 41, in create
    return reader(
  File "C:\Users\****\.conda\envs\python38\lib\site-packages\mikeio1d\result_reader_writer\result_reader_copier.py", line 59, in __init__
    self.result_data_copier = ResultDataCopier(self.data)
TypeError: No method matches given arguments for ResultDataCopier..ctor: (<class 'DHI.Mike1D.ResultDataAccess.ResultData'>)
```

**To Reproduce**
You can download the attached file which is test data for mikeplus.
[Sirius.zip](https://github.com/DHI/mikeio1d/files/14382043/Sirius.zip)

1. `import mikeplus`
2. `import mikeio1d`
3. read results file using `Res1D`

Code
``` 
from mikeplus import DataTableAccess
from mikeplus.engines import Engine1D
import mikeio1d
'''
db_path = r'D:\Drainage\MIKEpy\mikepluspy-main\tests\testdata\Db\Sirius\Sirius.sqlite'
data_access = DataTableAccess(db_path)
data_access.open_database()

print(data_access.is_database_open())
data_access.close_database()
'''
# replace the result file path
result = mikeio1d.res1d.Res1D(r'D:\Drainage\MIKEpy\mikepluspy-main\tests\testdata\Db\Sirius\Sirius_m1d - Result Files\Sirius_1_DEMOBaseDefault_Network_HD.res1d')
print(result)

```

**Screenshots**
![image](https://github.com/DHI/mikeio1d/assets/150115714/df5dc441-a858-406e-bd30-495dbd1a5734)
![image](https://github.com/DHI/mikeio1d/assets/150115714/55ae010b-d562-4288-a50a-4f9430382b2a)
[Sirius.zip](https://github.com/DHI/mikeio1d/files/14382043/Sirius.zip)

**System information:**
 - Python version: [Python 3.8] / [Python 3.12]
 - MIKE IO version [MIKE IO 1D v0.6]

**Comment by gedaskir** [comment]
Could you try to import the packages in the following way by specifying the `MIKE_INSTALL_PATH`:

```python
import os
import mikeplus
os.environ['MIKE_INSTALL_PATH'] = str(mikeplus.MikeImport.ActiveProduct().InstallRoot)

import mikeio1d
res1d = mikeio1d.Res1D(r'D:\Drainage\MIKEpy\mikepluspy-main\tests\testdata\Db\Sirius\Sirius_m1d - Result Files\Sirius_1_DEMOBaseDefault_Network_HD.res1d')
```
and let us know if it works for you.

**Comment by ZhaoNianZH** [comment]
Thanks! It works now. 👍
